### PR TITLE
unistd/sys.c: fix execle to populate envp from independent va_list

### LINKED ISSUE #1457: `execle()` can trigger page fault in kernel
Image

Image

Reproduction (ia32-generic-qemu):
```c
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

int main(void)
{
        int ret;

        ret = execle("/bin/ls", "ls", "-l", NULL, NULL);
        printf("execle ret: %d errno: %d\n", ret, errno);

        return 0;
}
```

**NOTE:** When I used `execle("/bin/ls", "ls", NULL, NULL);`, it worked fine

### LINKED ISSUE #1465: `execle()` doesn't pass environment
Reproduction (ia32-generic-qemu):

First program:
```c
#include <stdio.h>

extern char **environ;

int main(void)
{
        int i = 1;
        char *var;

        puts("Printing environment...");

        while ((var = *environ++)) {
                printf("%d: %s\n", i++, var);
        }

        return 0;
}
```

Second program:
```c
#include <stdio.h>
#include <errno.h>
#include <unistd.h>

int main(void)
{
        int ret;
        char *env[] = {
                "USER=adam",
                "SHELL=bash",
                "HOME=/home/adam",
                "PATH=/usr/bin:/bin",
                "EDITOR=nano",
                NULL
        };

        errno = 0;
        ret = execle("/usr/bin/print_env", "print_env", NULL, env);
        printf("execv ret: %d errno: %d\n", ret, errno);

        return 1;
}
```

Image

### PR DESCRIPTION
**Pull request by adamgreloch**
Previous implementation seemed to make non-portable assumptions about va_list reuse/consumption in the callee. As a result

```
execle("/bin/ls", "ls", "-l", NULL, NULL);
```

would cause `envp` to point to garbage on riscv64.

This change uses fresh va_list to ensure safe access to both handles.

Fixes: phoenix-rtos/phoenix-rtos-project#1457
Fixes: phoenix-rtos/phoenix-rtos-project#1465

JIRA: RTOS-1295

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [X] New test added: https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/481
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

File: unistd/sys.c [hunk 1]
```diff
@@ -281,12 +286,22 @@ int execlp(const char *file, const char *arg, ...)
...
 {
-	va_list args;
+	va_list args, argsCopy;
 	char **argv, **envp;
 	int err;
 
 	va_start(args, arg);
-	argv = argv_gather(arg, args);
+
+	/* copy args to argsCopy and gather from it so that args is left untouched for envp */
```
Comment (etiaro) [inline unistd/sys.c]: I would rather see in this comment that va_list gets invalidated when (even partially) consumed  inside callee, to follow the convention of "why" instead of "what" comments.

**Review by etiaro — COMMENTED** [review]
Generally fine, just a little comment suggestion.

Also, you could consider just using va_start/va_end twice, I guess that's a little cleaner..

File: unistd/sys.c (hunk 1 above)
Comment (adamgreloch) [reply unistd/sys.c]: good suggestion, thanks

**Review by etiaro — APPROVED** [review]
LGTM
